kind: Namespace
apiVersion: v1
metadata:
  name: dev-nginx-demo-arm
  labels:
    name: dev-nginx-demo-arm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-demo-arm
  labels:
    app: nginx-demo-arm
  namespace: dev-nginx-demo-arm
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo-arm
        tier: frontend
    spec:
      containers:
      - image: containerstack/nginx-demo-arm:latest
        name: nginx-demo-arm
        env:
        ports:
        - containerPort: 80
          name: nginx-demo-arm
      nodeSelector:
        instancetype: I1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-arm
  labels:
    app: nginx-demo-arm
  namespace: dev-nginx-demo-arm
spec:
  ports:
    - port: 80
  selector:
    app: nginx-demo-arm
    tier: frontend
  type: NodePort
