apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prod-cs-web
  labels:
    app: prod-cs-web
  namespace: prod-cs-web-temp
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-cs-web
        tier: frontend
    spec:
      containers:
      - image: remonlam/nginx-demo:latest
        name: prod-cs-web
        env:
        ports:
        - containerPort: 80
          name: prod-cs-web
---
apiVersion: v1
kind: Service
metadata:
  name: prod-cs-web
  labels:
    app: prod-cs-web
  namespace: prod-cs-web-temp
spec:
  ports:
    - port: 80
  selector:
    app: prod-cs-web
    tier: frontend
  type: NodePort
